# Generated by Django 4.2.4 on 2023-09-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosssok',
            name='avalicao',
            field=models.ManyToManyField(to='avaliacoes.avaliacao'),
        ),
    ]
