# Generated by Django 4.2.4 on 2023-09-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
