# Generated by Django 4.2.4 on 2023-09-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='stars',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
